
pipeline {
    agent any

     tools {nodejs "node"}
     environment {
        DOCKER = 'sudo docker'
        TIME_ZONE = 'Asia/Seoul'
        PROFILE = 'local'
        REGION = 'ap-northeast-2'
    }


stages {
    stage('prepare') {
        steps {
            dir('frontend/waterbell'){
                sh 'npm install'
               
            }
        }
    }
    stage('build') {
        steps {
            dir('frontend/waterbell'){
                sh 'npm run build'

                sh '''
                echo 'Dockerimage build'
                docker build -t docker-vue:0.0.1 .
                '''
            }
        }
    }
    stage('Deploy') {
        steps {
            dir('frontend/waterbell'){
                sh '''
                echo 'Deploy'
                docker stop WaterBellFront
                docker rm WaterBellFront
                docker run -d -p 3000:3000 -v /etc/localtime:/etc/localtime:ro -e TZ=Asia/Seoul --name WaterBellFront docker-vue:0.0.1
                '''
            }
        }
    }
}
}
